### ISSUE TITLE
-Dgraal.AlwaysPreTouch

### ISSUE THREAD

**Issue by sydist** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#13]
I found this; i'm not sure if it turns on automatically when you use -XX:+AlwaysPreTouch though.

**Comment by couleurm** [comment]
what does it do?

**Comment by brucethemoose** [comment]
Yes, the `Dgrall` arguments are seemingly duplicates of the regular OpenJDK ones and enable the same functionality, but I will check this when I update the readme for GraalVM 22.3.0. There is probably a logging option that will tell you if pretouch is enabled or not.

All of the `Drgaal` arguments can be found here: https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks/blob/75ae126c561131888120df1b178379b67c22ef06/Flag_Dumps/All_Graal_Flags#L48

Feel free to dig through those and point out anything that looks interesting!

**Comment by brucethemoose** [comment]
I think this can be closed since it was already tested. Though feel free to re-open or make a new issue for similar questions.
