### ISSUE TITLE
high process priority is bad practice

### ISSUE THREAD

**Issue by getchoo** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#15]
[this](https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks#process-priority) section in the README.md - while it could help performance *slightly* - is not recommended. according to [microsoft](https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities):

> If a thread runs at the highest priority level for extended periods, other threads in the system will not get processor time. If several threads are set at high priority at the same time, the threads lose their effectiveness. The high-priority class should be reserved for threads that must respond to time-critical events. (...) The important point is that a high-priority thread should execute for a brief time, and only when it has time-critical work to perform.

minecraft is not time critical relative to system processes on windows that also use this priority, and in environments such as servers that have high uptime (or even clients for that matter) this has a potential for introducing instability. above normal would be a better option here in my opinion, as it would still have some priority while mitigating the risks of high priority

**Comment by brucethemoose** [comment]
Oh IDK how I missed the notification for this. Yeah that is a reasonable recommendation.
