### ISSUE TITLE
Azul JDK on windows

### ISSUE THREAD

**Issue by HyperSoop** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#19]
After a big/medium story I discovered that the launcher TL Legacy auto-downloads the Azul JDK which is stupid fast, way faster than GraalVM EE. It is mentioned in this guide:

> Azul's Prime OpenJDK is very fast since it hooks into llvm, but its currently incompatible with most mods and is linux-only. Get it from here: https://docs.azul.com/prime/prime-quick-start-tar

But the thing is, I'm on windows and this mysterious Azul JDK bundled by TLL runs for me (even after routing Prism Lancher to use it). And it is fully compatible with Simply Optimized (currently only the latest 1.18.x release tested). There clearly is something going on, Azul can be used on windows.

**Comment by HyperSoop** [comment]
After some testing, i can say: azul is great. Zulu gives a bit more FPS than Graal EE does, and conserves a lot on memory.

**Comment by HyperSoop** [comment]
Wait, so graal EE is not much better in most cases? You should probably mention that somewhere

**Comment by HyperSoop** [comment]
I think i'm stupid

**Comment by brucethemoose** [comment]
> Wait, so graal EE is not much better in most cases? You should probably mention that somewhere

It seems to depend on the environment. Graal uses more RAM and background CPU, so it seems to shine on higher end PCs, but there are also reports of it helping low end computers.

It also seems to help content-heavy mod loadouts more.

This is all just my subjective/informal impressions

**Comment by brucethemoose** [comment]
Oh also I accidentally mashed the reopen key on mobile, but feel free to reopen if you wish.
