### ISSUE TITLE
Azul Zulu on Windows

### ISSUE THREAD

**Issue by TH3N3WN00B** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#32]
[Azul zulu](https://www.azul.com/downloads/?package=jdk#download-openjdk) is aviable now on windows and MacOS

![image](https://user-images.githubusercontent.com/10799738/234387058-25414ebe-4e74-4fa7-a80c-5ae121e617e0.png)

![image](https://user-images.githubusercontent.com/10799738/234387155-5305ea01-493c-4b0b-aa57-ac5f38071a09.png)

**Comment by mucookul** [comment]
The Guide Talks about Platform Prime, not Zulu. Zulu is just a unmodified build of OpenJDK by Azul, it's been on windows for a while.

**Comment by TH3N3WN00B** [comment]
Oh, sorry, my bad
