### ISSUE TITLE
Numa Not Working?

### ISSUE THREAD

**Issue by JustCauseWhyNot** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#33]
I'm on gentoo and have numa compiled in the kernel, but for some reason according to [prism's log](https://gist.github.com/JustCauseWhyNot/1f779d58746a46e6e87640c84d909318) Numa Support isn't on. I'd appreciate any help available. Also how do I get garbage collector to stop having/causing lag spikes ranging between 150-400ms when using 32 render distance?

**Comment by radiomike** [comment]
Unless your system is multi-socketed - has more than one cpu - numa probably doesn't apply.

As far as long gc with 32 render distance, either assign more ram, or reduce your view distance. 32 view distance is a huge number of loaded chunks (4096 chunks vs 576 for the default view distance of 12) and as a result has a huge impact on memory usage. If you are playing modded, you can look at the spark mod `spark healthreport --memory` to see the difference. You can also use `spark gc` or `spark tickmonitor` to see what type of gc you are seeing - if the lag spikes are from old gc then you should definitely increase your assigned ram.

**Comment by JustCauseWhyNot** [comment]
Alrighty. Thank you very much for the support.
