### ISSUE TITLE
GraalVM EE actually has issues with some mods.

### ISSUE THREAD

**Issue by HyperSoop** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#6]
I can confirm Immersive Portals has issues with EE that don't present on CE. I have also seen people say other mods that touch the technicals of Minecraft are not well compatible. This is something that should be pointed out, after more information is acquired.

**Comment by HyperSoop** [comment]
Ooh, in the same configuration CE results in unbearable log spam with GL errors. Oofie.

**Comment by brucethemoose** [comment]
> Ooh, in the same configuration CE results in unbearable log spam with GL errors. Oofie.

Oh interesting. CE is basicaly OpenJDK, so I'm surprised it has any issues.

The immersive portals issue still happen with no arguments?

I will test immersive, but can you post a log for the GL thing?

**Comment by brucethemoose** [comment]
@HyperSoop you can fix this for now by rolling back to GraalVM  22.1.0 and removing the line `-Dgraal.EarlyGVN=true -Dgraal.StripMineCountedLoops=true`

**Comment by HyperSoop** [comment]
> > Ooh, in the same configuration CE results in unbearable log spam with GL errors. Oofie.
> 
> Oh interesting. CE is basicaly OpenJDK, so I'm surprised it has any issues.
> 
> The immersive portals issue still happen with no arguments?
> 
> I will test immersive, but can you post a log for the GL thing?

The log i'll send now, and also i'll try without flags in a bit.
`[20:30:20] [Render thread/INFO]: OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. The source and destination internal formats are not compatible.'` - like 20 of these per second.

**Comment by HyperSoop** [comment]
I see you have already figured out the problem with EE, i'll now also try to reproduce the CE log spam.

(Yes, i got it. It's only happening with the flags)

**Comment by brucethemoose** [comment]
> I see you have already figured out the problem with EE.

Not exactly :(. I know its some kind of entperprise compiler regression between 22.2.0 and, 22.1.0, but I would prefer to fix it in 22.2.0 without rolling back or disabling the whole enterprise compiler.

And yeah, I ran CE with the OpenJDK 17 flags, and I'm not getting that GL error... but I *have* seen that error before, when running the Iris mod.


Hence I'd like to see your whole log if possible, to know your hardware, environment and so on. But if I can't replicate it, you may have to take half the flags out at a time to narrow down which mod is bugging immportals out.

**Comment by HyperSoop** [comment]
> 

I actually have iris on that instance, so it's just poor compatibility with immptl and iris which is somewhat known.

**Comment by brucethemoose** [comment]
> > 
> 
> I actually have iris on that instance, so it's just poor compatibility with immptl and iris which is somewhat known.

Oh actually I get that as a standalone Iris issue on my RTX 2060, even with shaders disabled.

Its not a GraalVM-specific issue either, I don't think, but I will double check that. I've been meaning to report this as well, I will ping you if I do.

**Comment by brucethemoose** [comment]
Oh I've confirmed this breaks Iris too, you were right.

I've updated the args to remove the offending flag.

**Comment by brucethemoose** [comment]
So to summarize, one bug I thought was an immersive portals bug was actually a vanilla crash, the other (the VectorizeSIMD flag) only seems to break Iris.

You have any more details about what's breaking immersive portals?

**Comment by brucethemoose** [comment]
> > You have any more details about what's breaking immersive portals?
> 
> I don't know. My guess is immersive portals makes big changes to the area of rendering code affected, and that's why it makes the issue so noticable.

But whats the issue? I tried the dimension stack feature and building a portal in Graal, and both seem to work/look fine.

**Comment by HyperSoop** [comment]
> > > You have any more details about what's breaking immersive portals?
> > 
> > 
> > I don't know. My guess is immersive portals makes big changes to the area of rendering code affected, and that's why it makes the issue so noticable.
> 
> But whats the issue? I tried the dimension stack feature and building a portal in Graal EE, and both seem to work/look fine.

Maybe it was related to your arguments. I think we ahve already decided what the problem is...?

**Comment by brucethemoose** [comment]
I was mistaken before. I thought I was running into a startup crash with immersive portals, but turns out that was a vanilla issue.

**Comment by mllightitup** [comment]
Astral Sorcery does not display constellations in the book and in the telescope when the JDK from GraalVM is installed. Happened to me and my friend on Enigmatica 6 Expert modpack. Or displays for a while and then disappears.

**Comment by mllightitup** [comment]
I tried removing all the flags and some mods, but the only thing that helped was changing java to adoptium

**Comment by brucethemoose** [comment]
> Astral Sorcery does not display constellations in the book and in the telescope when the JDK from GraalVM is installed. Happened to me and my friend on Enigmatica 6 Expert modpack. Or displays for a while and then disappears.

I will try to reproduce this. But if you wish, you can disable these flags like so, as most are enabled by default: ```-Dgraal.UsePriorityInlining=false -Dgraal.Vectorization=false -Dgraal.OptDuplication=false -Dgraal.DetectInvertedLoopsAsCounted=false -Dgraal.LoopInversion=false -Dgraal.VectorizeHashes=false -Dgraal.EnterprisePartialUnroll=false -Dgraal.VectorizeSIMD=false -Dgraal.StripMineNonCountedLoops=false -Dgraal.SpeculativeGuardMovement=false -Dgraal.InfeasiblePathCorrelation=false -Dgraal.LoopRotation=false```

**Comment by brucethemoose** [comment]
Oh, and I have rolled back to GraalVM 22.1.0 EE myself. 22.2 seems like a funky release.

**Comment by brucethemoose** [comment]
The book and telescope work for me with the following block: ```-server -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -XX:+UseStringDeduplication -XX:+UseFastUnorderedTimeStamps -XX:+UseAES -XX:+UseAESIntrinsics -XX:AllocatePrefetchStyle=1 -XX:+UseLoopPredicate -XX:+RangeCheckElimination -XX:+EliminateLocks -XX:+DoEscapeAnalysis -XX:+UseCodeCacheFlushing -XX:+UseFastJNIAccessors -XX:+OptimizeStringConcat -XX:+UseCompressedOops -XX:+UseThreadPriorities -XX:+OmitStackTraceInFastThrow -XX:+TrustFinalNonStaticFields -XX:ThreadPriorityPolicy=1 -XX:+UseInlineCaches -XX:+RewriteBytecodes -XX:+RewriteFrequentPairs -XX:+UseNUMA -XX:-DontCompileHugeMethods -XX:+UseFPUForSpilling -XX:+UseXMMForArrayCopy -Djdk.nio.maxCachedBufferSize=262144 -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=false -Dgraal.Vectorization=false -Dgraal.OptDuplication=false -Dgraal.DetectInvertedLoopsAsCounted=false -Dgraal.LoopInversion=false -Dgraal.VectorizeHashes=false -Dgraal.EnterprisePartialUnroll=false -Dgraal.VectorizeSIMD=false -Dgraal.StripMineNonCountedLoops=false -Dgraal.SpeculativeGuardMovement=false -Dgraal.InfeasiblePathCorrelation=false -XX:+UseLargePages -XX:LargePageSizeInBytes=2m```

Gonna try to enable some of the graal options to narrow it down.

**Comment by brucethemoose** [comment]
@mllightitup 
I jumped the gun in my previous post, as I can't get this to actually happen in my E6E instance.

What version of GraalVM are yall using? And how long does it usually take to happen?
![2022-08-05_19 47 32](https://user-images.githubusercontent.com/8422224/183227082-e64da93d-5e05-420b-928d-5a9ab5c77ff0.jpg)
![2022-08-05_19 47 36](https://user-images.githubusercontent.com/8422224/183227083-b2be1040-2d9d-4ff4-ba8e-a47685c8cdb4.jpg)

**Comment by mllightitup** [comment]
I tried in java 17 graalvm ee 22.2.0
If you run an enigmatic server for example, there are flags in the default settings to make everything work on java 16+. And as I understood from the official discord, everything should work fine on java 16+ on the client too

**Comment by mllightitup** [comment]
![Screenshot_2022-08-06-04-32-49-07_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/43480503/183228376-b4679707-67e8-4fb0-85dd-13705f5bf924.jpg)
I just now noticed the first sentence. Maybe this is just one of those bugs.)

**Comment by mllightitup** [comment]
Can you try to replicate this on java 17 graalvm 22.2.0? Maybe the problem is with the java 17 from graal

**Comment by brucethemoose** [comment]
> I tried on java 17 graalvm ee 22.2.0 If you run an enigmatic server for example, there are flags in the default settings to make everything work on java 16+. And as I understood from the official discord, everything should work fine on java 16+ on the client too

It just errors out for me when I try to run Java 17, with a message saying I have to run Java 8, so I havent tried 17 yet.

Does this bug happen in Adoptium 17 too?

**Comment by mllightitup** [comment]
If you use multimc or polymc there is a checkbox "skip java compatibility check" or something like that

**Comment by mllightitup** [comment]
If the checkbox is active it allows you to use java 17

**Comment by mllightitup** [comment]
> Does this bug happen in Adoptium 17 too?

Nope. Adoptium 17 fixes this bug with astral sorcery

**Comment by brucethemoose** [comment]
> > Does this bug happen in Adoptium 17 too?
> 
> Nope. Adoptium 17 fixes this bug with astral sorcery

I have confirmed this. It even happens in GraalVM Community Edition!

And it doesn't happen in Graal EE for Java 8.

This is a weird one.

**Comment by Supersonicboss1** [comment]
I want to document this here for anyone having the same issue - on 1.18.2, TerraBlender seems to break with Java 17 EE **22.2.0,**  and for whatever reason, the same is not true with EE **22.1.0**

Error:
```
Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: SubTree needs at least one child
```

Something is **definitely** wrong with 22.2.0, at least for Minecraft.

**Comment by brucethemoose** [comment]
> I want to document this here for anyone having the same issue - on 1.18.2, TerraBlender seems to break with Java 17 EE **22.2.0,** and for whatever reason, the same is not true with EE **22.1.0**
> 
> Error:
> 
> ```
> Failed to load datapacks, can't proceed with server load
> java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: SubTree needs at least one child
> ```
> 
> Something is **definitely** wrong with 22.2.0, at least for Minecraft.

22.2.0 breaks vanilla with the default flags. It is indeed fishy.

**Comment by brucethemoose** [comment]
There was a possible 22.3.0 bug with particles mentioned in the discord. 

I couldn't reproduce it in a quick test, but if anyone else runs into it, please let me know.
